name: Build and Push Docker Image

on:
  push:
    branches:
      - master

permissions:
  contents: read               # for checking out code
  packages: write              # for pushing to GitHub Container Registry
  id-token: write              

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/contrafy/personal-page:latest
            ghcr.io/contrafy/personal-page:${{ github.sha }}

      - name: Verify image pushed
        run: echo "Image ghcr.io/contrafy/personal-page:${{ github.sha }} pushed successfully!"
